# Generated by Django 2.2.5 on 2019-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=80)),
                ('eage', models.IntegerField()),
                ('esal', models.FloatField()),
            ],
            options={
                'db_table': 'empinfo',
            },
        ),
    ]
